<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Информация о багаже</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        .baggage-info {
            margin-top: 30px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            color: #333;
        }

        .baggage-info h2 {
            font-size: 2em;
            margin-bottom: 20px;
            text-align: center;
        }

        .baggage-info ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .baggage-info li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="baggage-info">
        <h2>Где находятся багажные тележки</h2>
        <ul>
            <li>Перед входами в терминалы</li>
            <li>Перед выходами с автомобильных парковок</li>
            <li>На платформах терминала Аэроэкспресс после турникетов</li>
            <li>На выходе из терминала Аэроэкспресс в терминал Е, 2 этаж</li>
            <li>Перед переходом из терминала D в терминал Е, 3 этаж</li>
            <li>В залах выдачи багажа</li>
        </ul>

        <p>Максимальный вес на одной тележке: 150 кг. Корзина тележки выдерживает до 10 кг.</p>

        <p>Багажные тележки можно использовать для перевозки крупногабаритного багажа. Располагайте его так, чтобы он не падал с тележки, не блокировал проход и не мешал другим пассажирам.</p>

        <h2>Правила использования багажных тележек</h2>
        <ul>
            <li>Не выносите тележки за пределы терминала аэропорта</li>
            <li>Не используйте тележки на эскалаторах, траволаторах или лестницах</li>
            <li>Не перевозите людей на тележках</li>
            <li>Не используйте багажные тележки в межтерминальных переходах или не забирайте их в поезд</li>
            <li>Если вам больше не нужна тележка, не оставляйте ее на пути других пассажиров. Отодвиньте ее в сторону или верните к месту сбора тележек.</li>
        </ul>
    </div>
</div>
</body>
</html>
